// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spire/api/server/identity/v1/identity.proto

package identity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	types "github.com/spiffe/spire/proto/spire/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExchangeRequest struct {
	// Types that are valid to be assigned to Step:
	//	*ExchangeRequest_Params_
	//	*ExchangeRequest_ChallengeResponse
	//	*ExchangeRequest_X509Request
	//	*ExchangeRequest_JwtRequest
	Step                 isExchangeRequest_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{0}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

type isExchangeRequest_Step interface {
	isExchangeRequest_Step()
}

type ExchangeRequest_Params_ struct {
	Params *ExchangeRequest_Params `protobuf:"bytes,1,opt,name=params,proto3,oneof"`
}

type ExchangeRequest_ChallengeResponse struct {
	ChallengeResponse []byte `protobuf:"bytes,2,opt,name=challenge_response,json=challengeResponse,proto3,oneof"`
}

type ExchangeRequest_X509Request struct {
	X509Request *X509Request `protobuf:"bytes,3,opt,name=x509Request,proto3,oneof"`
}

type ExchangeRequest_JwtRequest struct {
	JwtRequest *JWTRequest `protobuf:"bytes,4,opt,name=jwtRequest,proto3,oneof"`
}

func (*ExchangeRequest_Params_) isExchangeRequest_Step() {}

func (*ExchangeRequest_ChallengeResponse) isExchangeRequest_Step() {}

func (*ExchangeRequest_X509Request) isExchangeRequest_Step() {}

func (*ExchangeRequest_JwtRequest) isExchangeRequest_Step() {}

func (m *ExchangeRequest) GetStep() isExchangeRequest_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeRequest) GetParams() *ExchangeRequest_Params {
	if x, ok := m.GetStep().(*ExchangeRequest_Params_); ok {
		return x.Params
	}
	return nil
}

func (m *ExchangeRequest) GetChallengeResponse() []byte {
	if x, ok := m.GetStep().(*ExchangeRequest_ChallengeResponse); ok {
		return x.ChallengeResponse
	}
	return nil
}

func (m *ExchangeRequest) GetX509Request() *X509Request {
	if x, ok := m.GetStep().(*ExchangeRequest_X509Request); ok {
		return x.X509Request
	}
	return nil
}

func (m *ExchangeRequest) GetJwtRequest() *JWTRequest {
	if x, ok := m.GetStep().(*ExchangeRequest_JwtRequest); ok {
		return x.JwtRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeRequest_Params_)(nil),
		(*ExchangeRequest_ChallengeResponse)(nil),
		(*ExchangeRequest_X509Request)(nil),
		(*ExchangeRequest_JwtRequest)(nil),
	}
}

type ExchangeRequest_Params struct {
	// The exchange data
	Data                 *types.IdentityExchangeData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ExchangeRequest_Params) Reset()         { *m = ExchangeRequest_Params{} }
func (m *ExchangeRequest_Params) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest_Params) ProtoMessage()    {}
func (*ExchangeRequest_Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{0, 0}
}

func (m *ExchangeRequest_Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest_Params.Unmarshal(m, b)
}
func (m *ExchangeRequest_Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest_Params.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest_Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest_Params.Merge(m, src)
}
func (m *ExchangeRequest_Params) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest_Params.Size(m)
}
func (m *ExchangeRequest_Params) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest_Params.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest_Params proto.InternalMessageInfo

func (m *ExchangeRequest_Params) GetData() *types.IdentityExchangeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExchangeResponse struct {
	// Types that are valid to be assigned to Step:
	//	*ExchangeResponse_X509Svid
	//	*ExchangeResponse_Jwtsvid
	//	*ExchangeResponse_Challenge
	Step                 isExchangeResponse_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{1}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

type isExchangeResponse_Step interface {
	isExchangeResponse_Step()
}

type ExchangeResponse_X509Svid struct {
	X509Svid *types.X509SVID `protobuf:"bytes,1,opt,name=x509svid,proto3,oneof"`
}

type ExchangeResponse_Jwtsvid struct {
	Jwtsvid *types.JWTSVID `protobuf:"bytes,2,opt,name=jwtsvid,proto3,oneof"`
}

type ExchangeResponse_Challenge struct {
	Challenge []byte `protobuf:"bytes,3,opt,name=challenge,proto3,oneof"`
}

func (*ExchangeResponse_X509Svid) isExchangeResponse_Step() {}

func (*ExchangeResponse_Jwtsvid) isExchangeResponse_Step() {}

func (*ExchangeResponse_Challenge) isExchangeResponse_Step() {}

func (m *ExchangeResponse) GetStep() isExchangeResponse_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeResponse) GetX509Svid() *types.X509SVID {
	if x, ok := m.GetStep().(*ExchangeResponse_X509Svid); ok {
		return x.X509Svid
	}
	return nil
}

func (m *ExchangeResponse) GetJwtsvid() *types.JWTSVID {
	if x, ok := m.GetStep().(*ExchangeResponse_Jwtsvid); ok {
		return x.Jwtsvid
	}
	return nil
}

func (m *ExchangeResponse) GetChallenge() []byte {
	if x, ok := m.GetStep().(*ExchangeResponse_Challenge); ok {
		return x.Challenge
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeResponse_X509Svid)(nil),
		(*ExchangeResponse_Jwtsvid)(nil),
		(*ExchangeResponse_Challenge)(nil),
	}
}

type RenewRequest struct {
	// Types that are valid to be assigned to Step:
	//	*RenewRequest_X509Request
	//	*RenewRequest_JwtRequest
	Step                 isRenewRequest_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RenewRequest) Reset()         { *m = RenewRequest{} }
func (m *RenewRequest) String() string { return proto.CompactTextString(m) }
func (*RenewRequest) ProtoMessage()    {}
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{2}
}

func (m *RenewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRequest.Unmarshal(m, b)
}
func (m *RenewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRequest.Marshal(b, m, deterministic)
}
func (m *RenewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRequest.Merge(m, src)
}
func (m *RenewRequest) XXX_Size() int {
	return xxx_messageInfo_RenewRequest.Size(m)
}
func (m *RenewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRequest proto.InternalMessageInfo

type isRenewRequest_Step interface {
	isRenewRequest_Step()
}

type RenewRequest_X509Request struct {
	X509Request *X509Request `protobuf:"bytes,1,opt,name=x509Request,proto3,oneof"`
}

type RenewRequest_JwtRequest struct {
	JwtRequest *JWTRequest `protobuf:"bytes,2,opt,name=jwtRequest,proto3,oneof"`
}

func (*RenewRequest_X509Request) isRenewRequest_Step() {}

func (*RenewRequest_JwtRequest) isRenewRequest_Step() {}

func (m *RenewRequest) GetStep() isRenewRequest_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *RenewRequest) GetX509Request() *X509Request {
	if x, ok := m.GetStep().(*RenewRequest_X509Request); ok {
		return x.X509Request
	}
	return nil
}

func (m *RenewRequest) GetJwtRequest() *JWTRequest {
	if x, ok := m.GetStep().(*RenewRequest_JwtRequest); ok {
		return x.JwtRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RenewRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RenewRequest_X509Request)(nil),
		(*RenewRequest_JwtRequest)(nil),
	}
}

type RenewResponse struct {
	// Types that are valid to be assigned to Step:
	//	*RenewResponse_X509Svid
	//	*RenewResponse_JwtResult
	Step                 isRenewResponse_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RenewResponse) Reset()         { *m = RenewResponse{} }
func (m *RenewResponse) String() string { return proto.CompactTextString(m) }
func (*RenewResponse) ProtoMessage()    {}
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{3}
}

func (m *RenewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewResponse.Unmarshal(m, b)
}
func (m *RenewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewResponse.Marshal(b, m, deterministic)
}
func (m *RenewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewResponse.Merge(m, src)
}
func (m *RenewResponse) XXX_Size() int {
	return xxx_messageInfo_RenewResponse.Size(m)
}
func (m *RenewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenewResponse proto.InternalMessageInfo

type isRenewResponse_Step interface {
	isRenewResponse_Step()
}

type RenewResponse_X509Svid struct {
	X509Svid *types.X509SVID `protobuf:"bytes,1,opt,name=x509svid,proto3,oneof"`
}

type RenewResponse_JwtResult struct {
	JwtResult *types.JWTSVID `protobuf:"bytes,2,opt,name=jwtResult,proto3,oneof"`
}

func (*RenewResponse_X509Svid) isRenewResponse_Step() {}

func (*RenewResponse_JwtResult) isRenewResponse_Step() {}

func (m *RenewResponse) GetStep() isRenewResponse_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *RenewResponse) GetX509Svid() *types.X509SVID {
	if x, ok := m.GetStep().(*RenewResponse_X509Svid); ok {
		return x.X509Svid
	}
	return nil
}

func (m *RenewResponse) GetJwtResult() *types.JWTSVID {
	if x, ok := m.GetStep().(*RenewResponse_JwtResult); ok {
		return x.JwtResult
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RenewResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RenewResponse_X509Svid)(nil),
		(*RenewResponse_JwtResult)(nil),
	}
}

type X509Request struct {
	Params               *X509Request_X509SVIDParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *X509Request) Reset()         { *m = X509Request{} }
func (m *X509Request) String() string { return proto.CompactTextString(m) }
func (*X509Request) ProtoMessage()    {}
func (*X509Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{4}
}

func (m *X509Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509Request.Unmarshal(m, b)
}
func (m *X509Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509Request.Marshal(b, m, deterministic)
}
func (m *X509Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509Request.Merge(m, src)
}
func (m *X509Request) XXX_Size() int {
	return xxx_messageInfo_X509Request.Size(m)
}
func (m *X509Request) XXX_DiscardUnknown() {
	xxx_messageInfo_X509Request.DiscardUnknown(m)
}

var xxx_messageInfo_X509Request proto.InternalMessageInfo

func (m *X509Request) GetParams() *X509Request_X509SVIDParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type X509Request_X509SVIDParams struct {
	// Required. ASN.1 DER encoded CSR. The CSR is used to convey the public
	// key. Optionally, the subject and any number of DNS SANs can also be set.
	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	// The desired TTL of the X509-SVID, in seconds. The server default will be
	// used if unset. The TTL is advisory only. The actual lifetime of the
	// X509-SVID may be lower depending on the remaining lifetime of the active
	// SPIRE Server CA.
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *X509Request_X509SVIDParams) Reset()         { *m = X509Request_X509SVIDParams{} }
func (m *X509Request_X509SVIDParams) String() string { return proto.CompactTextString(m) }
func (*X509Request_X509SVIDParams) ProtoMessage()    {}
func (*X509Request_X509SVIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{4, 0}
}

func (m *X509Request_X509SVIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509Request_X509SVIDParams.Unmarshal(m, b)
}
func (m *X509Request_X509SVIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509Request_X509SVIDParams.Marshal(b, m, deterministic)
}
func (m *X509Request_X509SVIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509Request_X509SVIDParams.Merge(m, src)
}
func (m *X509Request_X509SVIDParams) XXX_Size() int {
	return xxx_messageInfo_X509Request_X509SVIDParams.Size(m)
}
func (m *X509Request_X509SVIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_X509Request_X509SVIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_X509Request_X509SVIDParams proto.InternalMessageInfo

func (m *X509Request_X509SVIDParams) GetCsr() []byte {
	if m != nil {
		return m.Csr
	}
	return nil
}

func (m *X509Request_X509SVIDParams) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type JWTRequest struct {
	Params               *JWTRequest_JWTSVIDParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JWTRequest) Reset()         { *m = JWTRequest{} }
func (m *JWTRequest) String() string { return proto.CompactTextString(m) }
func (*JWTRequest) ProtoMessage()    {}
func (*JWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{5}
}

func (m *JWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRequest.Unmarshal(m, b)
}
func (m *JWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRequest.Marshal(b, m, deterministic)
}
func (m *JWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRequest.Merge(m, src)
}
func (m *JWTRequest) XXX_Size() int {
	return xxx_messageInfo_JWTRequest.Size(m)
}
func (m *JWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRequest proto.InternalMessageInfo

func (m *JWTRequest) GetParams() *JWTRequest_JWTSVIDParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type JWTRequest_JWTSVIDParams struct {
	// Required. List of audience claims to include in the JWT-SVID.
	// At least one must be set.
	Audience []string `protobuf:"bytes,1,rep,name=audience,proto3" json:"audience,omitempty"`
	// Desired TTL of the JWT-SVID, in seconds. The server default will be used
	// if unset. The TTL is advisory only. The actual lifetime of the JWT-SVID
	// may be lower depending on the remaining lifetime of the active SPIRE
	// Server CA.
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTRequest_JWTSVIDParams) Reset()         { *m = JWTRequest_JWTSVIDParams{} }
func (m *JWTRequest_JWTSVIDParams) String() string { return proto.CompactTextString(m) }
func (*JWTRequest_JWTSVIDParams) ProtoMessage()    {}
func (*JWTRequest_JWTSVIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{5, 0}
}

func (m *JWTRequest_JWTSVIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Unmarshal(m, b)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Marshal(b, m, deterministic)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRequest_JWTSVIDParams.Merge(m, src)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Size() int {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Size(m)
}
func (m *JWTRequest_JWTSVIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRequest_JWTSVIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRequest_JWTSVIDParams proto.InternalMessageInfo

func (m *JWTRequest_JWTSVIDParams) GetAudience() []string {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *JWTRequest_JWTSVIDParams) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func init() {
	proto.RegisterType((*ExchangeRequest)(nil), "spire.api.server.identity.v1.ExchangeRequest")
	proto.RegisterType((*ExchangeRequest_Params)(nil), "spire.api.server.identity.v1.ExchangeRequest.Params")
	proto.RegisterType((*ExchangeResponse)(nil), "spire.api.server.identity.v1.ExchangeResponse")
	proto.RegisterType((*RenewRequest)(nil), "spire.api.server.identity.v1.RenewRequest")
	proto.RegisterType((*RenewResponse)(nil), "spire.api.server.identity.v1.RenewResponse")
	proto.RegisterType((*X509Request)(nil), "spire.api.server.identity.v1.X509Request")
	proto.RegisterType((*X509Request_X509SVIDParams)(nil), "spire.api.server.identity.v1.X509Request.X509SVIDParams")
	proto.RegisterType((*JWTRequest)(nil), "spire.api.server.identity.v1.JWTRequest")
	proto.RegisterType((*JWTRequest_JWTSVIDParams)(nil), "spire.api.server.identity.v1.JWTRequest.JWTSVIDParams")
}

func init() {
	proto.RegisterFile("spire/api/server/identity/v1/identity.proto", fileDescriptor_25379ce627d0c156)
}

var fileDescriptor_25379ce627d0c156 = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xd1, 0x6e, 0x12, 0x41,
	0x14, 0x65, 0x0a, 0x45, 0xb8, 0x50, 0xad, 0x13, 0x4d, 0x70, 0x63, 0x0c, 0xf2, 0x84, 0x36, 0xce,
	0x52, 0x4a, 0x8d, 0xc6, 0x18, 0x93, 0xda, 0x26, 0x94, 0x44, 0xd3, 0x8c, 0x8d, 0x35, 0xbe, 0xe8,
	0x14, 0xa6, 0xb0, 0x0d, 0x2c, 0xeb, 0xce, 0x00, 0xed, 0xab, 0xff, 0xe0, 0x93, 0x4f, 0x7e, 0x82,
	0xdf, 0xe3, 0x7f, 0xf8, 0x6c, 0x76, 0x76, 0x66, 0x76, 0xa1, 0x09, 0x62, 0xea, 0xdb, 0xb0, 0xf7,
	0x9c, 0xb3, 0xe7, 0x9e, 0xbb, 0x77, 0x80, 0x2d, 0x11, 0x78, 0x21, 0x77, 0x59, 0xe0, 0xb9, 0x82,
	0x87, 0x53, 0x1e, 0xba, 0x5e, 0x8f, 0xfb, 0xd2, 0x93, 0x97, 0xee, 0x74, 0xdb, 0x9e, 0x49, 0x10,
	0x8e, 0xe5, 0x18, 0xdf, 0x57, 0x60, 0xc2, 0x02, 0x8f, 0xc4, 0x60, 0x62, 0x01, 0xd3, 0x6d, 0xa7,
	0x16, 0x4b, 0xc9, 0xcb, 0x80, 0x0b, 0xcb, 0xe4, 0x17, 0xdd, 0x01, 0xf3, 0xfb, 0x3c, 0x56, 0x70,
	0xee, 0xa5, 0x31, 0xe7, 0x33, 0x29, 0xa6, 0x5e, 0x4f, 0x97, 0x9c, 0x74, 0xe9, 0x62, 0xb7, 0xf1,
	0x3c, 0xa9, 0xd5, 0x7e, 0xaf, 0xc1, 0xad, 0x03, 0xad, 0x44, 0xf9, 0x97, 0x09, 0x17, 0x12, 0xbf,
	0x85, 0x7c, 0xc0, 0x42, 0x36, 0x12, 0x15, 0x54, 0x45, 0xf5, 0x52, 0xb3, 0x45, 0x96, 0xb9, 0x23,
	0x0b, 0x74, 0x72, 0xa4, 0xb8, 0xed, 0x0c, 0xd5, 0x2a, 0xd8, 0x05, 0xdc, 0x1d, 0xb0, 0xe1, 0x90,
	0xfb, 0x7d, 0xfe, 0x29, 0xe4, 0x22, 0x18, 0xfb, 0x82, 0x57, 0xd6, 0xaa, 0xa8, 0x5e, 0x6e, 0x67,
	0xe8, 0x6d, 0x5b, 0xa3, 0xba, 0x84, 0xdf, 0x40, 0x29, 0xb2, 0xa9, 0x05, 0x2b, 0x59, 0xe5, 0xe2,
	0xd1, 0x72, 0x17, 0x1f, 0x12, 0x42, 0x3b, 0x43, 0xd3, 0x7c, 0xdc, 0x01, 0x38, 0x9f, 0x49, 0xa3,
	0x96, 0x53, 0x6a, 0xf5, 0xe5, 0x6a, 0x9d, 0x93, 0xe3, 0x44, 0x2c, 0xc5, 0x76, 0x5e, 0x41, 0x3e,
	0xee, 0x0f, 0xef, 0x42, 0xae, 0xc7, 0x24, 0xd3, 0x19, 0x3d, 0xd4, 0x7a, 0x2a, 0x64, 0x72, 0xa8,
	0xa5, 0x4c, 0x34, 0xfb, 0x4c, 0x32, 0xaa, 0xe0, 0x7b, 0x79, 0xc8, 0x09, 0xc9, 0x83, 0xda, 0x0f,
	0x04, 0x9b, 0x49, 0x72, 0xba, 0xf1, 0x1d, 0x28, 0x98, 0xf9, 0x68, 0xdd, 0xbb, 0x73, 0xba, 0x51,
	0x93, 0xef, 0xde, 0x1f, 0xee, 0xb7, 0x33, 0xd4, 0x02, 0x71, 0x03, 0x6e, 0xe8, 0x79, 0xab, 0x4c,
	0x4b, 0xcd, 0x3b, 0x73, 0x9c, 0xce, 0xc9, 0xb1, 0xa6, 0x18, 0x18, 0x7e, 0x00, 0x45, 0x1b, 0xba,
	0x4a, 0x37, 0x9a, 0x43, 0xf2, 0xc8, 0x7a, 0xfc, 0x89, 0xa0, 0x4c, 0xb9, 0xcf, 0x67, 0x26, 0xc9,
	0x85, 0xc1, 0xa0, 0xff, 0x3a, 0x98, 0xb5, 0xeb, 0x0c, 0xc6, 0x7a, 0xfe, 0x8a, 0x60, 0x43, 0x7b,
	0xbe, 0x4e, 0xa8, 0x2d, 0x28, 0x2a, 0x71, 0x31, 0x19, 0xca, 0xbf, 0xc4, 0x9a, 0x00, 0xad, 0x89,
	0x6f, 0x08, 0x4a, 0xa9, 0xbe, 0xf1, 0xd1, 0xc2, 0x46, 0x3d, 0x5b, 0x39, 0x32, 0xeb, 0x2e, 0xfe,
	0xea, 0xcc, 0x4e, 0x39, 0x2d, 0xb8, 0x39, 0x5f, 0xc1, 0x9b, 0x90, 0xed, 0x8a, 0x50, 0xbd, 0xa0,
	0x4c, 0xa3, 0x63, 0xf4, 0x44, 0xca, 0xa1, 0x72, 0xbf, 0x4e, 0xa3, 0x63, 0xed, 0x3b, 0x02, 0x48,
	0x12, 0xbc, 0xb2, 0xe8, 0x4f, 0x57, 0xcd, 0xde, 0x74, 0xbf, 0x60, 0xea, 0x25, 0x6c, 0xcc, 0x15,
	0xb0, 0x03, 0x05, 0x36, 0xe9, 0x79, 0xdc, 0xef, 0xf2, 0x0a, 0xaa, 0x66, 0xeb, 0x45, 0x6a, 0x7f,
	0x5f, 0x75, 0xd7, 0xfc, 0x85, 0xa0, 0x60, 0x36, 0x07, 0x8f, 0xa0, 0x60, 0xd6, 0x03, 0x3f, 0xf9,
	0xa7, 0x0b, 0xc8, 0x21, 0xab, 0xc2, 0xe3, 0x0f, 0xa4, 0x8e, 0x1a, 0x08, 0x7f, 0x86, 0x75, 0xf5,
	0xd5, 0xe0, 0xc7, 0xcb, 0xc9, 0xe9, 0x75, 0x70, 0xb6, 0x56, 0xc2, 0xc6, 0x6f, 0xd9, 0x3b, 0xf8,
	0xf8, 0xba, 0xef, 0xc9, 0xc1, 0xe4, 0x94, 0x74, 0xc7, 0x23, 0x57, 0x04, 0xde, 0xd9, 0x19, 0x77,
	0xe3, 0x9b, 0x59, 0x5d, 0xc5, 0xee, 0xb2, 0xff, 0x8b, 0x17, 0xe6, 0x7c, 0x9a, 0x57, 0xe0, 0x9d,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x57, 0xbd, 0x08, 0x5f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	// Exchanges a platform-specific identity document with an SVID.
	// A bidirectional stream is provided to facilitate the exchange methods
	// that require challenge/response. The result can be an X509 SVID or a JWT-SVID.
	Exchange(ctx context.Context, opts ...grpc.CallOption) (Identity_ExchangeClient, error)
	// Renews the current SVID returning a new SVID. The new SVID is not enabled
	// on the server side until its first use.
	//
	// The caller must present an active SVID, i.e. the SVID
	// returned by the Exchange or the most recent Renew call.
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (Identity_ExchangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Identity_serviceDesc.Streams[0], "/spire.api.server.identity.v1.Identity/Exchange", opts...)
	if err != nil {
		return nil, err
	}
	x := &identityExchangeClient{stream}
	return x, nil
}

type Identity_ExchangeClient interface {
	Send(*ExchangeRequest) error
	Recv() (*ExchangeResponse, error)
	grpc.ClientStream
}

type identityExchangeClient struct {
	grpc.ClientStream
}

func (x *identityExchangeClient) Send(m *ExchangeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *identityExchangeClient) Recv() (*ExchangeResponse, error) {
	m := new(ExchangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identityClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.identity.v1.Identity/Renew", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	// Exchanges a platform-specific identity document with an SVID.
	// A bidirectional stream is provided to facilitate the exchange methods
	// that require challenge/response. The result can be an X509 SVID or a JWT-SVID.
	Exchange(Identity_ExchangeServer) error
	// Renews the current SVID returning a new SVID. The new SVID is not enabled
	// on the server side until its first use.
	//
	// The caller must present an active SVID, i.e. the SVID
	// returned by the Exchange or the most recent Renew call.
	Renew(context.Context, *RenewRequest) (*RenewResponse, error)
}

// UnimplementedIdentityServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityServer struct {
}

func (*UnimplementedIdentityServer) Exchange(srv Identity_ExchangeServer) error {
	return status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (*UnimplementedIdentityServer) Renew(ctx context.Context, req *RenewRequest) (*RenewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Renew not implemented")
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityServer).Exchange(&identityExchangeServer{stream})
}

type Identity_ExchangeServer interface {
	Send(*ExchangeResponse) error
	Recv() (*ExchangeRequest, error)
	grpc.ServerStream
}

type identityExchangeServer struct {
	grpc.ServerStream
}

func (x *identityExchangeServer) Send(m *ExchangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *identityExchangeServer) Recv() (*ExchangeRequest, error) {
	m := new(ExchangeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Identity_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.identity.v1.Identity/Renew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spire.api.server.identity.v1.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Renew",
			Handler:    _Identity_Renew_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _Identity_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "spire/api/server/identity/v1/identity.proto",
}
