// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spire/server/identityexchanger/identityexchanger.proto

package indentityexchanger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	plugin "github.com/spiffe/spire/proto/spire/common/plugin"
	types "github.com/spiffe/spire/proto/spire/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a request for an identity exchange
type ExchangeRequest struct {
	// An identity exchange starts with identity exchange data, and the
	// response of this request may have a challenge. If it has a challenge
	// then this message contains the response to that challenge
	//
	// Types that are valid to be assigned to Step:
	//	*ExchangeRequest_Data
	//	*ExchangeRequest_Response
	Step                 isExchangeRequest_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6889fb4d90fed7f, []int{0}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

type isExchangeRequest_Step interface {
	isExchangeRequest_Step()
}

type ExchangeRequest_Data struct {
	Data *types.IdentityExchangeData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ExchangeRequest_Response struct {
	Response []byte `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*ExchangeRequest_Data) isExchangeRequest_Step() {}

func (*ExchangeRequest_Response) isExchangeRequest_Step() {}

func (m *ExchangeRequest) GetStep() isExchangeRequest_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeRequest) GetData() *types.IdentityExchangeData {
	if x, ok := m.GetStep().(*ExchangeRequest_Data); ok {
		return x.Data
	}
	return nil
}

func (m *ExchangeRequest) GetResponse() []byte {
	if x, ok := m.GetStep().(*ExchangeRequest_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeRequest_Data)(nil),
		(*ExchangeRequest_Response)(nil),
	}
}

// Represents a response of an identity exchange
type ExchangeResponse struct {
	// Types that are valid to be assigned to Step:
	//	*ExchangeResponse_Challenge
	//	*ExchangeResponse_Response_
	Step                 isExchangeResponse_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6889fb4d90fed7f, []int{1}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

type isExchangeResponse_Step interface {
	isExchangeResponse_Step()
}

type ExchangeResponse_Challenge struct {
	Challenge []byte `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type ExchangeResponse_Response_ struct {
	Response *ExchangeResponse_Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*ExchangeResponse_Challenge) isExchangeResponse_Step() {}

func (*ExchangeResponse_Response_) isExchangeResponse_Step() {}

func (m *ExchangeResponse) GetStep() isExchangeResponse_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeResponse) GetChallenge() []byte {
	if x, ok := m.GetStep().(*ExchangeResponse_Challenge); ok {
		return x.Challenge
	}
	return nil
}

func (m *ExchangeResponse) GetResponse() *ExchangeResponse_Response {
	if x, ok := m.GetStep().(*ExchangeResponse_Response_); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeResponse_Challenge)(nil),
		(*ExchangeResponse_Response_)(nil),
	}
}

type ExchangeResponse_Response struct {
	// The SPIFFE ID that resulted from the identity exchange
	SpiffeId *types.SPIFFEID `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Optional list of selectors
	Selectors            []*types.Selector `protobuf:"bytes,2,rep,name=selectors,proto3" json:"selectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExchangeResponse_Response) Reset()         { *m = ExchangeResponse_Response{} }
func (m *ExchangeResponse_Response) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse_Response) ProtoMessage()    {}
func (*ExchangeResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6889fb4d90fed7f, []int{1, 0}
}

func (m *ExchangeResponse_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse_Response.Unmarshal(m, b)
}
func (m *ExchangeResponse_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse_Response.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse_Response.Merge(m, src)
}
func (m *ExchangeResponse_Response) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse_Response.Size(m)
}
func (m *ExchangeResponse_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse_Response.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse_Response proto.InternalMessageInfo

func (m *ExchangeResponse_Response) GetSpiffeId() *types.SPIFFEID {
	if m != nil {
		return m.SpiffeId
	}
	return nil
}

func (m *ExchangeResponse_Response) GetSelectors() []*types.Selector {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeRequest)(nil), "spire.server.indentityexchanger.ExchangeRequest")
	proto.RegisterType((*ExchangeResponse)(nil), "spire.server.indentityexchanger.ExchangeResponse")
	proto.RegisterType((*ExchangeResponse_Response)(nil), "spire.server.indentityexchanger.ExchangeResponse.Response")
}

func init() {
	proto.RegisterFile("spire/server/identityexchanger/identityexchanger.proto", fileDescriptor_c6889fb4d90fed7f)
}

var fileDescriptor_c6889fb4d90fed7f = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x6e, 0x62, 0x29, 0xc9, 0x54, 0x51, 0x07, 0x84, 0x25, 0x88, 0xc6, 0x05, 0x65, 0xf5, 0x62,
	0x52, 0x53, 0x50, 0x10, 0x44, 0xd0, 0xb6, 0x36, 0x77, 0x25, 0xde, 0x48, 0x6f, 0x24, 0x4d, 0x4e,
	0xb2, 0x03, 0xd9, 0x99, 0x31, 0x33, 0x11, 0xf7, 0x11, 0x7c, 0x37, 0x1f, 0x4a, 0x76, 0x7e, 0xf6,
	0x27, 0xbb, 0xb0, 0xee, 0x55, 0x92, 0x73, 0xbe, 0x9f, 0x39, 0x5f, 0xce, 0xa0, 0x77, 0x52, 0xd0,
	0x0e, 0x12, 0x09, 0xdd, 0x2f, 0xe8, 0x12, 0x5a, 0x01, 0x53, 0x54, 0xcd, 0xe1, 0x77, 0x39, 0x2d,
	0x58, 0xb3, 0xab, 0x42, 0x44, 0xc7, 0x15, 0xc7, 0xcf, 0x35, 0x8f, 0x18, 0x1e, 0xa1, 0x6c, 0x08,
	0x8b, 0x62, 0x23, 0x5c, 0xf2, 0xd9, 0x8c, 0xb3, 0x44, 0xb4, 0x7d, 0x43, 0xdd, 0xc3, 0x48, 0x44,
	0x91, 0x41, 0xa8, 0xb9, 0x00, 0x99, 0x48, 0x41, 0xeb, 0x1a, 0x68, 0xb5, 0xb3, 0x07, 0x2d, 0x94,
	0x8a, 0x5b, 0xeb, 0x68, 0xbc, 0xde, 0x1b, 0x9e, 0xcf, 0x60, 0xc6, 0x02, 0x3d, 0xbc, 0xb4, 0x95,
	0x1c, 0x7e, 0xf6, 0x20, 0x15, 0x7e, 0x8f, 0x8e, 0xab, 0x42, 0x15, 0x23, 0x2f, 0xf6, 0x26, 0xa7,
	0xe9, 0x0b, 0x62, 0x06, 0xd0, 0x2a, 0x24, 0xb3, 0x2a, 0x8e, 0x73, 0x51, 0xa8, 0xe2, 0xfa, 0x28,
	0xd7, 0x04, 0xfc, 0x14, 0x05, 0x1d, 0x48, 0xc1, 0x99, 0x84, 0x91, 0x1f, 0x7b, 0x93, 0xfb, 0xd7,
	0x47, 0xf9, 0xb2, 0xf2, 0xf9, 0x04, 0x1d, 0x4b, 0x05, 0x62, 0xfc, 0xc7, 0x47, 0x8f, 0x56, 0x96,
	0xa6, 0x89, 0x9f, 0xa1, 0xb0, 0x9c, 0x16, 0x6d, 0x0b, 0xac, 0x01, 0x6d, 0xbc, 0xe0, 0xae, 0x4a,
	0xf8, 0xfb, 0x40, 0xfa, 0x34, 0xfd, 0x40, 0xf6, 0x04, 0x4b, 0x86, 0x26, 0xc4, 0xbd, 0xac, 0x1f,
	0x2b, 0x92, 0x28, 0x58, 0x9e, 0x22, 0x45, 0xa1, 0x89, 0xf7, 0x07, 0xad, 0xec, 0xf8, 0x4f, 0x36,
	0xc6, 0xff, 0x76, 0x93, 0x5d, 0x5d, 0x5d, 0x66, 0x17, 0x79, 0x60, 0x70, 0x59, 0x85, 0xcf, 0x51,
	0xe8, 0x62, 0x97, 0x23, 0x3f, 0xbe, 0xb7, 0xcd, 0xb1, 0xdd, 0x7c, 0x85, 0x73, 0x59, 0xa4, 0x7f,
	0x7d, 0xf4, 0x78, 0x18, 0x69, 0x87, 0x25, 0x0a, 0xdc, 0x07, 0x3e, 0x3b, 0x60, 0x4c, 0xfd, 0xfb,
	0xa2, 0xb7, 0x07, 0x07, 0x33, 0xf1, 0xce, 0x3c, 0x7c, 0x8b, 0xc2, 0x2f, 0x9c, 0xd5, 0xb4, 0xe9,
	0x3b, 0xc0, 0x2f, 0xad, 0x86, 0x59, 0x4a, 0x62, 0xb7, 0x71, 0xd9, 0x77, 0x56, 0xaf, 0xf6, 0xc1,
	0x6c, 0xae, 0x35, 0x7a, 0xf0, 0x15, 0xd4, 0x8d, 0x6e, 0x67, 0xac, 0xe6, 0xf8, 0xf5, 0x4e, 0xe2,
	0x06, 0xc6, 0x79, 0xbc, 0xf9, 0x1f, 0xa8, 0x5d, 0xb1, 0x4f, 0xb7, 0x1f, 0x1b, 0xaa, 0xa6, 0xfd,
	0xdd, 0x02, 0x6d, 0x6f, 0x4a, 0x62, 0x2e, 0x81, 0xde, 0xf6, 0x64, 0xf3, 0x0e, 0x6f, 0x25, 0x73,
	0x77, 0xa2, 0x61, 0xe7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xb5, 0x83, 0xee, 0xed, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityExchangerClient is the client API for IdentityExchanger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityExchangerClient interface {
	// Exchange a platform-specific identity document with an SVID
	Exchange(ctx context.Context, opts ...grpc.CallOption) (IdentityExchanger_ExchangeClient, error)
	// Standard SPIRE plugin RPCs
	Configure(ctx context.Context, in *plugin.ConfigureRequest, opts ...grpc.CallOption) (*plugin.ConfigureResponse, error)
	GetPluginInfo(ctx context.Context, in *plugin.GetPluginInfoRequest, opts ...grpc.CallOption) (*plugin.GetPluginInfoResponse, error)
}

type identityExchangerClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityExchangerClient(cc grpc.ClientConnInterface) IdentityExchangerClient {
	return &identityExchangerClient{cc}
}

func (c *identityExchangerClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (IdentityExchanger_ExchangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IdentityExchanger_serviceDesc.Streams[0], "/spire.server.indentityexchanger.IdentityExchanger/Exchange", opts...)
	if err != nil {
		return nil, err
	}
	x := &identityExchangerExchangeClient{stream}
	return x, nil
}

type IdentityExchanger_ExchangeClient interface {
	Send(*ExchangeRequest) error
	Recv() (*ExchangeResponse, error)
	grpc.ClientStream
}

type identityExchangerExchangeClient struct {
	grpc.ClientStream
}

func (x *identityExchangerExchangeClient) Send(m *ExchangeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *identityExchangerExchangeClient) Recv() (*ExchangeResponse, error) {
	m := new(ExchangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identityExchangerClient) Configure(ctx context.Context, in *plugin.ConfigureRequest, opts ...grpc.CallOption) (*plugin.ConfigureResponse, error) {
	out := new(plugin.ConfigureResponse)
	err := c.cc.Invoke(ctx, "/spire.server.indentityexchanger.IdentityExchanger/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityExchangerClient) GetPluginInfo(ctx context.Context, in *plugin.GetPluginInfoRequest, opts ...grpc.CallOption) (*plugin.GetPluginInfoResponse, error) {
	out := new(plugin.GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, "/spire.server.indentityexchanger.IdentityExchanger/GetPluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityExchangerServer is the server API for IdentityExchanger service.
type IdentityExchangerServer interface {
	// Exchange a platform-specific identity document with an SVID
	Exchange(IdentityExchanger_ExchangeServer) error
	// Standard SPIRE plugin RPCs
	Configure(context.Context, *plugin.ConfigureRequest) (*plugin.ConfigureResponse, error)
	GetPluginInfo(context.Context, *plugin.GetPluginInfoRequest) (*plugin.GetPluginInfoResponse, error)
}

// UnimplementedIdentityExchangerServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityExchangerServer struct {
}

func (*UnimplementedIdentityExchangerServer) Exchange(srv IdentityExchanger_ExchangeServer) error {
	return status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (*UnimplementedIdentityExchangerServer) Configure(ctx context.Context, req *plugin.ConfigureRequest) (*plugin.ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (*UnimplementedIdentityExchangerServer) GetPluginInfo(ctx context.Context, req *plugin.GetPluginInfoRequest) (*plugin.GetPluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}

func RegisterIdentityExchangerServer(s *grpc.Server, srv IdentityExchangerServer) {
	s.RegisterService(&_IdentityExchanger_serviceDesc, srv)
}

func _IdentityExchanger_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityExchangerServer).Exchange(&identityExchangerExchangeServer{stream})
}

type IdentityExchanger_ExchangeServer interface {
	Send(*ExchangeResponse) error
	Recv() (*ExchangeRequest, error)
	grpc.ServerStream
}

type identityExchangerExchangeServer struct {
	grpc.ServerStream
}

func (x *identityExchangerExchangeServer) Send(m *ExchangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *identityExchangerExchangeServer) Recv() (*ExchangeRequest, error) {
	m := new(ExchangeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IdentityExchanger_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(plugin.ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityExchangerServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.server.indentityexchanger.IdentityExchanger/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityExchangerServer).Configure(ctx, req.(*plugin.ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityExchanger_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(plugin.GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityExchangerServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.server.indentityexchanger.IdentityExchanger/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityExchangerServer).GetPluginInfo(ctx, req.(*plugin.GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityExchanger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spire.server.indentityexchanger.IdentityExchanger",
	HandlerType: (*IdentityExchangerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _IdentityExchanger_Configure_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _IdentityExchanger_GetPluginInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _IdentityExchanger_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "spire/server/identityexchanger/identityexchanger.proto",
}
