// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spire/types/identityexchange.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdentityExchangeData struct {
	// The type of identity exchange data. This is typically the name of the plugin
	// that produced that data
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The identity exchange data payload
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityExchangeData) Reset()         { *m = IdentityExchangeData{} }
func (m *IdentityExchangeData) String() string { return proto.CompactTextString(m) }
func (*IdentityExchangeData) ProtoMessage()    {}
func (*IdentityExchangeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c72289282c6ed704, []int{0}
}

func (m *IdentityExchangeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityExchangeData.Unmarshal(m, b)
}
func (m *IdentityExchangeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityExchangeData.Marshal(b, m, deterministic)
}
func (m *IdentityExchangeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityExchangeData.Merge(m, src)
}
func (m *IdentityExchangeData) XXX_Size() int {
	return xxx_messageInfo_IdentityExchangeData.Size(m)
}
func (m *IdentityExchangeData) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityExchangeData.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityExchangeData proto.InternalMessageInfo

func (m *IdentityExchangeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IdentityExchangeData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*IdentityExchangeData)(nil), "spire.types.IdentityExchangeData")
}

func init() {
	proto.RegisterFile("spire/types/identityexchange.proto", fileDescriptor_c72289282c6ed704)
}

var fileDescriptor_c72289282c6ed704 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x2e, 0xc8, 0x2c,
	0x4a, 0xd5, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0xcf, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9,
	0x4c, 0xad, 0x48, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x06, 0xab, 0xd1, 0x03, 0xab, 0x51, 0x72, 0xe1, 0x12, 0xf1, 0x84, 0x2a, 0x73, 0x85, 0x2a, 0x73,
	0x49, 0x2c, 0x49, 0x14, 0x12, 0xe2, 0x62, 0x01, 0x29, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x27, 0xed, 0x28, 0xcd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24,
	0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2, 0x82, 0xcc, 0xb4, 0xb4, 0x54, 0x7d, 0x88, 0x53, 0xc0, 0x76,
	0xea, 0x23, 0x39, 0x2b, 0x89, 0x0d, 0x2c, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x98, 0x0f,
	0xf4, 0x1a, 0xac, 0x00, 0x00, 0x00,
}
